# Gems
gems: [jekyll-paginate]

# Site settings
title: Who I am
email: balunjozef@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jozefbalun.github.io" # the base hostname & protocol for your site

github_username: jozefbalun


name: Jozef Balún

color:
  dark: fff #333

#social network
social:
  - title: facebook
    url: https://www.facebook.com/vpjozef
  - title: bitbucket
    url: http://bitbucket.org/balunjozef
  - title: github
    url: http://github.com/jozefbalun

markdown: kramdown
#permalink: /blog/:year/:month/:day/:title
permalink: pretty

footer:
  copyright: Who I am 2016
  social: Follow me


paginate: 5
paginate_path: "/blog/page:num/"
sass:
    sass_dir: _sass
